### ISSUE TITLE
crear api mid para tesoreria, el api centralizara los procesos de giros,avances y demas

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_mid#1]
crear el codigo basico con beego para un api mid el cual se encargara de gestionar las peticiones que necesite el sistema de tesoreria, ya sea de giros, avances, ingresos, etc

incluye dockerizacion

**Comment by Jeisson005** [comment]
Se realiza lo siguiente:

- [ ] Se crea API MID
- [ ] Se refactoriza
- [ ] Se configura docker, docker compose y variables de entorno iniciales
- [ ] Archivo readme

**Comment by Jeisson005** [comment]
Commits:
[15fdb84](https://github.com/udistrital/tesoreria_mid/commit/15fdb84e344efca588b41d2d4ffef695e83f2360)
[6a608d1](https://github.com/udistrital/tesoreria_mid/commit/6a608d1a6d7dcb9cd30a8f5689dcc31e5d0bf5ce)
[b54ff45](https://github.com/udistrital/tesoreria_mid/commit/b54ff45282707e2427828660dd89a09056fcd2ae)
[e6c91c3](https://github.com/udistrital/tesoreria_mid/commit/e6c91c3106ccaf330be8681584e626e763c730ee)
